### ISSUE TITLE
[6/14 Study with E]

### ISSUE THREAD

**Issue by ami-ryu** [DeveloperCookie/DailyAlgorithm#164]
## TODO:
- [x] Tree order별 serialize, deserialize
- [ ] 16.1 직접 디버거로 테스트
- [ ] variants
- [ ] 17.4 - v2 다른 방안 모색
- [ ] 19.3
- [ ] 각자 서비스에 대한 모델을 통해 20.13을 따라해보자
- [ ] Chapter 10 이후 내용 정독

-----

### Tree order별 Deserialize

- Inorder, Preorder 데이터로 Binary Tree 만들기 https://github.com/WoolimRyu/DailyAlgorithm/issues/121
- Preorder traversal 데이터로 BST 그리기 https://github.com/WoolimRyu/DailyAlgorithm/issues/65
- Preorder과 null값 Markers로 Binary Tree 만들어내기 https://github.com/WoolimRyu/DailyAlgorithm/issues/49
- 종합 https://github.com/WoolimRyu/DailyAlgorithm/issues/48

### Serialize
- Inorder traversal with O(1) space https://github.com/WoolimRyu/DailyAlgorithm/issues/47
```python3
class BinarySearchTree(object):
    ...
    def in_order_traversal(self):
        def _in_order_traversal(root):
            if root is None:
                pass
            else:
                _in_order_traversal(root.left)
                print(root.data)
                _in_order_traversal(root.right)
        _in_order_traversal(self.root)
```
- Preorder
```python3
class BinarySearchTree(object):
    ...
    def pre_order_traversal(self):
        def _pre_order_traversal(root):
            if root is None:
                pass
            else:
                print(root.data)
                _pre_order_traversal(root.left)
                _pre_order_traversal(root.right)
        _pre_order_traversal(self.root)
```
- Postorder
```python3
class BinarySearchTree(object):
    ...
    def post_order_traversal(self):
        def _post_order_traversal(root):
            if root is None:
                pass
            else:
                _post_order_traversal(root.left)
                _post_order_traversal(root.right)
                print(root.data)
        _post_order_traversal(self.root)
```

----
### 16.1 Dynamic Programming

----
### 16.1 Variants

----
### 17.4 Variants 2

----
### 19.3
- thread 정리 
https://www.notion.so/ryudirector/Python-Thread-77115c131a7449488fe4cfaeedcfd0e5

-
