### ISSUE TITLE
[EPI Col4 List]

### ISSUE THREAD

**Issue by ami-ryu** [DeveloperCookie/DailyAlgorithm#171]
- [ ] Sudoku 짜기 https://github.com/WoolimRyu/DailyAlgorithm/issues/181
- [x] 4.9 : https://github.com/WoolimRyu/DailyAlgorithm/issues/172 : 10진법의 정수가 Palindrome 인지 판단하기 
- [x] 5.3 : https://github.com/WoolimRyu/DailyAlgorithm/issues/173 : 2개의 배열로 된 정수 곱셈하기
- [x] 5.10 (V) : https://github.com/WoolimRyu/DailyAlgorithm/issues/174 : 배열의 순열 구하기
- [x] 5.15 : https://github.com/WoolimRyu/DailyAlgorithm/issues/175 : Random Subset 뽑기
- [x] 6.9 (V2) https://github.com/WoolimRyu/DailyAlgorithm/issues/177 : 로마표기법을 10진법으로 바꾸기 (잘 이해는 안됨;)
- [x] 6.11 https://github.com/WoolimRyu/DailyAlgorithm/issues/178 : 사인곡선으로 문장 출력하기
- [x] 7.11 (V) https://github.com/WoolimRyu/DailyAlgorithm/issues/179 : Singly or Doubly Linked List 가 회문인지 판단하기
- [x] 8.4 https://github.com/WoolimRyu/DailyAlgorithm/issues/180 : Normalize Pathnames
- [x] 9.13 https://github.com/WoolimRyu/DailyAlgorithm/issues/49 : Preorder traversal, markers 로 Binary Tree 만들기 (변형= PostOrder, InOrder인 경우)
- [x] 9.16 (V2) https://github.com/WoolimRyu/DailyAlgorithm/issues/52 : Compute Right Sibling Tree
- [ ] 10.6 https://github.com/WoolimRyu/DailyAlgorithm/issues/182 : Max-Heap 에서 K Largest Element 구하기

2부
- [ ] 11.6 2D Sorted Array에서 검색하기 https://github.com/WoolimRyu/DailyAlgorithm/issues/184
- [ ] 11.7 https://github.com/WoolimRyu/DailyAlgorithm/issues/185
- [ ] 12.9
- [ ] 13.8
- [ ] 14.7
- [ ] 15.6
- [ ] 15.10
- [ ] 16.12
- [ ] 17.8
- [ ] 18.5
- [ ] 20.9
- [ ] 20.2
